name: aavishkarapp
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+1
  firebase_auth:
  firebase_core:
  firebase_database:
  firebase_storage:
  url_launcher: ^3.0.3
  flutter_webview_plugin: ^0.3.10+1
  flutter_facebook_login:
  cached_network_image: ^2.0.0
  firebase_messaging: ^5.1.4
  google_sign_in:
  crypto: ^2.0.3
  carousel_slider:
  flutter_swiper:
  barcode_scan: any
  intl: ^0.15.7
  palette_generator: ^0.2.0
  path_provider: ^1.5.1
  #intro_slider: ^1.0.7
  share: ^0.5.3
  google_maps_flutter: ^0.5.20+6
  location: ^2.3.5
  http: ^0.12.0+3
  sliding_up_panel: ^0.3.6
  dio: ^3.0.8
  flame: ^0.17.3
  google_fonts: ^0.3.2
  image_picker: ^0.6.0+17
  flutter_staggered_grid_view: ^0.3.0
  flutter_speed_dial: ^1.2.5
  intro_slider: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1


flutter_icons:
    android: true
    ios: true
    image_path: "images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

# flutter:
#   fonts:
#    - family:  MyFlutterApp
#      fonts:
#       - asset: fonts/MyFlutterApp.ttf
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CustomFonts
      fonts:
       - asset: lib/util/fonts/fonts/CustomFonts.ttf
    - family: WhatsappIcon
      fonts:
       - asset: lib/util/fonts/whatsappicon/whatsappiconfonts/Whatsappicon.ttf

    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - fonts/Orbitron-Medium.ttf
    - images/
    - images/gifs/
    - images/Contributors/
    - assets/
    - assets/images/
    - assets/Aarohan_logo.jpg    
    - assets/INTRO1.png
    - assets/INTRO2.png
    - assets/INTRO3.png
    - assets/AU1.png
    - assets/AU2.png
    - assets/AU3.png
    - assets/AU4.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
